Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -160,6 +160,14 @@ jobs:
           docker logs xray
           docker ps -as
           docker logs caddy
+          echo -e "${RED}Final testing in progress${RESET}"
+          for i in {1..3}; do
+              curl -s -x socks5://localhost:64949 https://ipinfo.io/ip && { echo -e "${GREEN}Success${RESET}"; break; } || { echo -e "${RED}Attempt $i failed. Retrying in 5 seconds...${RESET}"; for j in {1..5}; do echo -e "${YELLOW}Waiting... ${j} seconds${RESET}"; sleep 1; done; }
+
+              if [ "$i" -eq 3 ]; then
+                  echo -e "${RED}Failed after 3 attempts, Final testing failure...${RESET}"
+              fi
+          done
 
       - name: Run Docker ps every 5 seconds for 30 minutes
         run: |
