Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -78,6 +78,31 @@ jobs:
               exit 1
           fi
 
+          cat <<EOF > $WORKING_DIR/etc/xray/az.json
+          {"log":{"access":"","error":"","loglevel":"warning"},"inbounds":[{"listen":"::","port":64949,"protocol":"socks","settings":{"auth":"noauth","udp":true},"tag":"socks"}],"outbounds":[{"tag":"proxy","protocol":"vless","settings":{"vnext":[{"address":"bebecar.com","port":443,"users":[{"id":"54212000-0000-0000-0000-000000000000","encryption":"none"}]}]},"streamSettings":{"network":"ws","security":"tls","tlsSettings":{"allowInsecure":false,"serverName":"animation-bread-mobiles-msgid.trycloudflare.com"},"wsSettings":{"path":"/vlessws","headers":{"Host":"animation-bread-mobiles-msgid.trycloudflare.com"}}},"mux":{}},{"tag":"direct","protocol":"freedom","settings":{}},{"tag":"block","protocol":"blackhole","settings":{}}],"routing":{"domainStrategy":"AsIs","rules":[{"type":"field","port":"0-65535","outboundTag":"proxy"}]}}
+
+          EOF
+
+          server_name=$(grep -oP '[a-zA-Z0-9._-]+\.trycloudflare\.com' $WORKING_DIR/cloudflared/cfed.log | tail -n 1)
+          sed -i "s/\"serverName\":\"[^\"]*\"/\"serverName\":\"$server_name\"/" $WORKING_DIR/etc/xray/az.json
+          sed -i "s/\"Host\":\"[^\"]*\"/\"Host\":\"$server_name\"/" $WORKING_DIR/etc/xray/az.json
+          cat $WORKING_DIR/etc/xray/az.json
+
+          sudo docker run -itd \
+            --name=xrayc \
+            --privileged \
+            --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --cap-add=NET_BIND_SERVICE \
+            --network=host \
+            --restart=always \
+            -v $WORKING_DIR/etc/xray/az.json:/etc/xray/config.json \
+            -v $WORKING_DIR/dev/shm:$WORKING_DIR/dev/shm \
+            teddysun/xray
+
+          CONTAINER_NAME="xrayc"; if docker ps --filter "name=$CONTAINER_NAME" --format '{{.Names}}' | grep -wq "$CONTAINER_NAME"; then echo "$(date +"%Y-%m-%d %H:%M:%S") === Container $CONTAINER_NAME is running."; else echo "$(date +"%Y-%m-%d %H:%M:%S") === Container $CONTAINER_NAME is not running."; fi
+
+          for i in {1..3}; do if curl -x socks5://localhost:64949 https://ipinfo.io/ip; then echo -e "${GREEN}Success${RESET}"; exit 0; else echo -e "${RED}Attempt $i failed. Retrying in 5 seconds...${RESET}"; for j in {1..5}; do echo -e "${YELLOW}Waiting... ${j} seconds${RESET}"; sleep 1; done; fi; done; echo -e "${RED}Failed after 3 attempts${RESET}"; exit 1
+
+
           echo -e "${GREEN}Restart cloudflared${RESET}"
           # sudo docker restart cloudflared
           echo -e "${RED}Wait for 10 seconds${RESET}"
