Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -104,13 +104,17 @@ jobs:
               curl -s -x socks5://localhost:64949 https://ipinfo.io/ip && { echo -e "${GREEN}Success${RESET}"; break; } || { echo -e "${RED}Attempt $i failed. Retrying in 5 seconds...${RESET}"; for j in {1..5}; do echo -e "${YELLOW}Waiting... ${j} seconds${RESET}"; sleep 1; done; }
 
               if [ "$i" -eq 3 ]; then
-                  echo -e "${RED}Failed after 3 attempts, restarting xray container...${RESET}"
-                  sudo docker restart xray
+                  echo -e "${RED}Failed after 3 attempts, restarting containers...${RESET}"
+                  sudo docker kill xray; sudo docker stop xray
+                  sudo docker kill xrayc; sudo docker stop xrayc
+                  sudo docker kill caddy; sudo docker stop caddy
+                  sudo docker kill cloudflared; sudo docker stop cloudflared
+                  sudo rm -rf $WORKING_DIR/dev/shm/*
+                  sleep 1
+                  sudo docker restart $(docker ps -asq)
               fi
           done
 
-          echo -e "${GREEN}Restart cloudflared${RESET}"
-          # sudo docker restart cloudflared
           echo -e "${RED}Wait for 10 seconds${RESET}"
           for i in {10..1}; do
             echo -e "${YELLOW}Waiting... ${i} seconds${RESET}"
@@ -162,7 +166,7 @@ jobs:
           docker logs caddy
           echo -e "${RED}Final testing in progress${RESET}"
           for i in {1..3}; do
-              curl -s -x socks5://localhost:64949 https://ipinfo.io/ip && { echo -e "${GREEN}Success${RESET}"; break; } || { echo -e "${RED}Attempt $i failed. Retrying in 5 seconds...${RESET}"; for j in {1..5}; do echo -e "${YELLOW}Waiting... ${j} seconds${RESET}"; sleep 1; done; }
+              curl -s -x socks5://localhost:64949 https://ipinfo.io/ip && { echo -e "${GREEN}Final testing Success${RESET}"; break; } || { echo -e "${RED}Attempt $i failed. Retrying in 5 seconds...${RESET}"; for j in {1..5}; do echo -e "${YELLOW}Waiting... ${j} seconds${RESET}"; sleep 1; done; }
 
               if [ "$i" -eq 3 ]; then
                   echo -e "${RED}Failed after 3 attempts, Final testing failure...${RESET}"
