Update pages.yml

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -42,13 +42,7 @@ jobs:
           preCommands: |
             echo "*** pre commands ***"
             echo ${{ env.RESPONSE_SUCCESS }}
-            if [ "$RESPONSE_SUCCESS" = "false" ]; then
-              echo "Project not found, creating new project..."
-              wrangler pages project create $MY_PROJECT_NAME --production-branch main
-            else
-              echo "Project already exists, no action needed."
-            fi
-
+            [ "$RESPONSE_SUCCESS" = "false" ] && echo "Project not found, creating new project..." && wrangler pages project create $MY_PROJECT_NAME --production-branch main || echo "Project already exists, no action needed."
           postCommands: |
             echo "*** post commands ***"
           command: |
