Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -112,20 +112,119 @@ jobs:
       - name: Upload Artifact
         uses: actions/upload-artifact@v3
         with:
-          name: caddy-${{ env.ASSET_NAME }}
+          name: chisel-${{ env.ASSET_NAME }}
           path: ./path/to/ready/*
-          retention-days: 1
+          # retention-days: 5
+
+  push-releases:
+    needs:
+      - autocheck
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      # - name: Setup Variables
+      #   env:
+      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #     # GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
+      #     CONTENT_PATH: "src/chisel/chisel.version"
+      #   run: |
+      #     # echo "CADDY_VERSION=$(curl -fsSL -H "Authorization: Bearer ${GH_TOKEN}" -X GET https://api.github.com/repos/${{ github.repository }}/contents/${{ env.CONTENT_PATH }} | jq -r .content | head -1 | base64 -d)" >> $GITHUB_ENV
+      #     echo "CADDY_VERSION=$(cat "${{ env.CONTENT_PATH }}" | head -n1)" >> $GITHUB_ENV
+
+      - run: mkdir -p path/to/artifact; install -d path/to/artifact
+      - run: mkdir -p path/to/ready; install -d path/to/ready
+      - name: Download Artifact
+        id: download
+        uses: actions/download-artifact@v3
+        with:
+          path: path/to/artifact
+
+      - name: Ready Upload files
+        run: |
+          for i in path/to/artifact/*/*; do echo "Copy ${i} to path/to/ready"; cp -fr ${i} path/to/ready; done
+          ls -lhR path/to/ready
+
+      - name: Delete old release
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          # GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
+        run: |
+          TARGET_TAG="chisel"
+          # https://docs.github.com/en/rest/git/refs#get-a-reference
+          TARGET_HTTP_CODE=$(curl -sI -w "%{http_code}" -o "/dev/null" \
+            -H "Authorization: Bearer ${GH_TOKEN}" \
+            https://api.github.com/repos/${{ github.repository }}/git/ref/tags/${TARGET_TAG} )
+
+          # https://docs.github.com/en/rest/releases/releases#get-a-release-by-tag-name
+          # TARGET_HTTP_CODE=$(curl -sI -w "%{http_code}" -o "/dev/null" \
+          #   -H "Authorization: Bearer ${GH_TOKEN}" \
+          #   https://api.github.com/repos/${{ github.repository }}/releases/tags/${TARGET_TAG} )
+
+          if [[ ${TARGET_HTTP_CODE} != 200 ]]; then
+          # if [[ "$TARGET_HTTP_CODE" -ne 200 ]]; then
+            # echo "Fail: ${TARGET_HTTP_CODE}"
+            # echo "No target tag or release found, skip delete."
+            echo -e "\033[1;40;96m$(date '+%F %T') === Fail: \033[0m\e[30;48;5;1m${TARGET_HTTP_CODE}\e[0m"
+            echo -e "\033[1;40;91m$(date '+%F %T') === No target tag or release found, skip delete. \033[0m"
+          else
+            # echo "Success: ${TARGET_HTTP_CODE}"
+            echo -e "\033[1;40;92m$(date '+%F %T') === Success: \033[0m\e[30;48;5;2m${TARGET_HTTP_CODE}\e[0m"
+            # gh release delete "${TARGET_TAG}" -y --cleanup-tag || echo -e "\033[1;40;96m$(date '+%F %T') === Fail: \033[0m\e[30;48;5;1m${TARGET_TAG} release not found\e[0m"
+            gh release delete "${TARGET_TAG}" --yes --cleanup-tag || echo -e "\033[1;40;96m$(date '+%F %T') === Fail: \033[0m\e[30;48;5;1m${TARGET_TAG} release not found\e[0m"
+            # echo "Target tag or release ${TARGET_TAG} deleted Complete!"
+
+            while true; do
+            # until false; do
+            echo -e "\e[30;48;5;12m$(date '+%F %T') === check release exist\e[0m"
+
+            TARGET_HTTP_CODE_TAG=$(curl -sI -w "%{http_code}" -o "/dev/null" \
+              -H "Authorization: Bearer ${GH_TOKEN}" \
+              https://api.github.com/repos/${{ github.repository }}/git/ref/tags/${TARGET_TAG} )
+
+            TARGET_HTTP_CODE_RELEASE=$(curl -sI -w "%{http_code}" -o "/dev/null" \
+              -H "Authorization: Bearer ${GH_TOKEN}" \
+              https://api.github.com/repos/${{ github.repository }}/releases/tags/${TARGET_TAG} )
+
+            if [[ ${TARGET_HTTP_CODE_TAG} == 200 ]] &>/dev/null; then
+            curl -sL \
+              -X DELETE \
+              -H "Authorization: Bearer ${GH_TOKEN}" \
+              https://api.github.com/repos/${{ github.repository }}/git/refs/tags/${TARGET_TAG} &>/dev/null
+            fi
+
+            if [[ ${TARGET_HTTP_CODE_TAG} == 404 && ${TARGET_HTTP_CODE_RELEASE} == 404 ]] &>/dev/null; then
+            echo -e "\e[30;48;5;14m$(date '+%F %T') === release is no exist ready to upload\e[0m"
+            sleep 1
+            break 49
+            else
+            echo -e "\e[30;48;5;11m$(date '+%F %T') === release exist retrying\e[0m"
+            fi
+
+            sleep 3
+            done
+
+            echo -e "\033[1;40;94m$(date '+%F %T') === Target tag or release \e[0m\e[30;48;5;4m${TARGET_TAG}\e[0m\033[1;40;94m deleted Complete! \033[0m"
+          fi
 
       # - name: Upload to GitHub Release for all platform
       #   env:
       #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       #     # GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
-      #     # CONTENT_PATH: "src/chisel/chisel.version"
+      #     CONTENT_PATH: "src/chisel/chisel.version"
       #   run: |
       #     TARGET_TAG="chisel"
-      #     if [[ "$(gh api repos/{owner}/{repo}/tags --jq '.[].name')" = "${TARGET_TAG}" ]]; then
-      #     gh release upload "${TARGET_TAG}" path/to/ready/* --clobber
-      #     else
+      #     TARGET_VERSION=$(cat ${{ env.CONTENT_PATH }})
       #     gh release create "${TARGET_TAG}" path/to/ready/* --title "Chisel Rolling Release" \
-      #     --notes "Chisel Version: <code>[v1.9.1](https://github.com/jpillora/chisel/releases/tag/v1.9.1)</code><br><br>**These are automatically updated builds of the latest commit.**"
-      #     fi
+      #     --notes "Chisel Version: <code>[${TARGET_VERSION}](https://github.com/caddyserver/caddy/releases/tag/${TARGET_VERSION})</code><br><br>**These are automatically updated builds of the latest commit.**"
+
+      - name: Upload to GitHub Release for all platform
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          # GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
+          # CONTENT_PATH: "src/chisel/chisel.version"
+        run: |
+          TARGET_TAG="chisel"
+          gh release create "${TARGET_TAG}" path/to/ready/* --title "Chisel Rolling Release" \
+          --notes "Chisel Version: <code>[v1.9.1](https://github.com/jpillora/chisel/releases/tag/v1.9.1)</code><br><br>**These are automatically updated builds of the latest commit.**"
